CREATE TABLE trips (
    id BIGSERIAL PRIMARY KEY,
    product_id BIGINT NOT NULL,
    brand_name VARCHAR(255),
    category VARCHAR(255),
    date VARCHAR(50),
    trip_type VARCHAR(100),
    trip_no VARCHAR(100),
    invoice_no VARCHAR(100),
    vehicle_name VARCHAR(255),
    vehicle_no VARCHAR(100),
    engine_no VARCHAR(100),
    chassis_no VARCHAR(100),
    driver_name VARCHAR(255),
    driver_mobile VARCHAR(20),
    helper_name VARCHAR(255),
    load_point VARCHAR(255),
    unload_point VARCHAR(255),
    destination VARCHAR(255),
    route VARCHAR(255),
    district VARCHAR(100),
    quantity DECIMAL(10,2),
    unit_price DECIMAL(10,2),
    total_rate DECIMAL(10,2),
    cash DECIMAL(10,2),
    advance DECIMAL(10,2),
    due DECIMAL(10,2),
    bill_no VARCHAR(100),
    bill_date VARCHAR(50),
    payment_type VARCHAR(50),
    truck_size VARCHAR(50),
    weight DECIMAL(10,2),
    fuel_type VARCHAR(50),
    fuel_cost DECIMAL(10,2),
    transport_type VARCHAR(100),
    remarks TEXT,
    status VARCHAR(50),
    created_by VARCHAR(255),
    approved_by VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_trips_product_id ON trips(product_id);