CREATE TABLE bills (
    id BIGSERIAL PRIMARY KEY,
    category VARCHAR(100),
    product_id BIGINT not null,
    vehicle_no VARCHAR(100),
    customer_name VARCHAR(255),
    challan_no VARCHAR(100),
    distributor_name VARCHAR(255),
    dealer_name VARCHAR(255),
    driver_name VARCHAR(255),
    from_location VARCHAR(255),
    destination VARCHAR(255),
    product VARCHAR(255),
    portfolio VARCHAR(100),
    goods VARCHAR(255),
    quantity DECIMAL(10,2),
    bike_qty INT,
    vehicle_size VARCHAR(50),
    status VARCHAR(50),
    unload_charge DECIMAL(10,2),
    vehicle_rent_with_vat_tax DECIMAL(10,2),
    vehicle_rent DECIMAL(10,2),
    dropping DECIMAL(10,2),
    alt5 DECIMAL(10,2),
    vat10 DECIMAL(10,2),
    total_rate DECIMAL(10,2),
    advance DECIMAL(10,2),
    due DECIMAL(10,2),
    total DECIMAL(10,2),
    profit DECIMAL(10,2),
    body_fare DECIMAL(10,2),
    fuel_cost DECIMAL(10,2),
    amount DECIMAL(10,2),
    total_amount DECIMAL(10,2),
    do_number TEXT,
    co_number TEXT,
    created_at TIMESTAMPTZ
);